Run ./gradlew assembleRelease --no-daemon

ERROR: JAVA_HOME is set to an invalid directory: /opt/hostedtoolcache/jdk/17.0.0/zulu

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Error: Process completed with exit code 1.
